skip_tags: true
clone_depth: 1

os: Visual Studio 2015

services:
   - mongodb

# Flask support for Python 3.x
# is still under development
environment:
   matrix:
      - PYTHON_HOME: C:\Python27
        FLASK_VERSION: 0.9
      - PYTHON_HOME: C:\Python27
        FLASK_VERSION: 0.10.1

platform:
   - x86
   - x64

install:
   - appveyor DownloadFile https://bootstrap.pypa.io/get-pip.py
   - '%PYTHON_HOME%\python get-pip.py'

build_script:
   - uname -a
   - df -h
   # Build into own virtualenv in order
   # to control the build environment
   - '%PYTHON_HOME%\Scripts\pip install virtualenv'
   - '%PYTHON_HOME%\Scripts\virtualenv venv'
   - venv\Scripts\activate
   - python -V
   - 'python -m pip install pip setuptools --ignore-installed'
   - 'pip install Flask==%FLASK_VERSION%'
   - pip install pymongo
   - pip install tweepy
   - pip install unittest2

test_script: python twitterApp\twitterUpdateTests.py
